version: "3"
services: 
    container_auth-db:
      image: postgres:11
      container_name: auth_db
      restart: always
      environment:
        - POSTGRES_DB=auth-db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=123456
      ports: 
        - 5432:5432

    container_product-db:
      image: postgres:11
      container_name: product_db
      restart: always
      environment:
        - POSTGRES_DB=product-db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=123456
      ports: 
        - 5433:5432

    container_sales-db:
      image: mongo
      container_name: sales_db
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME="admin"
        - MONGO_INITDB_DATABASE="sales"
        - MONGO_INITDB_ROOT_PASSWORD=123456
      ports: 
        - 27017:27017
        - 28017:28017
    
    auth-api:
      build: './auth-api'
      container_name: auth_api
      environment:
        - PORT=8080
      ports: 
        - 8080:8080

    product-api:
      build: './product-api'
      container_name: product_api
      environment:
        - PORT=8081
      ports: 
        - 8081:8081

    sales-api:
      build: './sales-api'
      container_name: sales_api
      environment:
        - PORT=8082
      ports: 
        - 8082:8082        


    container_sales_rabbit:
      image: rabbitmq:3-management
      container_name: sales-rabbit
      ports: 
        - 5672:5672
        - 25676:25676
        - 15672:15672